# Generated by Django 3.1.3 on 2020-11-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='col_two',
            field=models.CharField(default='', max_length=200),
        ),
    ]
